application: gonativeclient
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /demo
  static_files: static/index.html
  upload: static/index\.html

- url: /demo/.*
  static_files: static/index.html
  upload: static/index\.html

- url: /static/home/(.*)
  static_files: static/home/\1
  upload: static/home/.*

- url: /static
  static_dir: static

- url: /.*
  script: gonacl.application

skip_files:
- src/.*
